# SPDX-FileCopyrightText: 2019-2020 Magenta ApS
# SPDX-License-Identifier: MPL-2.0
version: "3.9"
services:
  sd_changed_at:
    build:
      context: .
    environment:
      SD_GLOBAL_FROM_DATE: "2022-01-01"
      SD_INSTITUTION_IDENTIFIER: MA
      SD_PASSWORD: password1
      SD_USER: SYMAGENTA
      SD_JOB_FUNCTION: JobPositionIdentifier
      SD_MONTHLY_HOURLY_DIVIDE: 9000
      SD_IMPORT_RUN_DB: /app/rundb.sqlite3
      MUNICIPALITY_CODE: 123
      MUNICIPALITY_NAME: "MAGENTA KOMMUNE"
      MORA_BASE: http://mo
      CLIENT_ID: "dipex"
      CLIENT_SECRET: "603f1c82-d012-4d04-9382-dbe659c533fb"
      AUTH_SERVER: "http://keycloak:8080/auth"

      APP_DBPASSWORD: super_secret_sd_payload_password
    depends_on:
      sd-db-init:
        condition: service_completed_successfully
    networks:
      - os2mo_default
    ports:
      - 8000:8000/tcp
    volumes:
      - ./:/app/
  sd-db:
    image: postgres:11.7  # Set image in global.sls
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    networks:
      os2mo_default:
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 30s
  sd-db-init:
    image: magentaaps/postgres-keycloak-init:12.7-11.7  # Set image in global.sls
    environment:
      POSTGRES_HOST: sd-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      KEYCLOAK_DB_NAME: sd_payload
      KEYCLOAK_DB_USER: sd_payload
      KEYCLOAK_DB_PASSWORD: super_secret_sd_payload_password
    networks:
      os2mo_default:
    depends_on:
      sd-db:
        condition: service_healthy

networks:
  os2mo_default:
    external: true
